# Generated by Django 4.0.5 on 2022-06-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='host_has_ball',
        ),
        migrations.AddField(
            model_name='friendship',
            name='mutual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='do_exit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='do_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='show_friend_info_screen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
