# Generated by Django 4.0.5 on 2022-06-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_remove_match_host_has_ball_friendship_mutual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='skin1_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendship',
            name='skin2_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
