# Generated by Django 4.0.5 on 2022-07-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_player_abc_alter_match_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='abc',
        ),
    ]
