# Generated by Django 4.0.5 on 2022-07-03 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0006_remove_player_abc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathertokens',
            name='received_daily_token',
        ),
        migrations.AddField(
            model_name='weathertokens',
            name='date_of_last_daily_claim',
            field=models.DateField(default=datetime.date(1969, 1, 1)),
        ),
    ]
