# Generated by Django 4.0.5 on 2022-07-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0007_remove_weathertokens_received_daily_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='guest_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='waiting', to='social_app.player'),
        ),
    ]
