# Generated by Django 4.0.5 on 2022-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0007_remove_weathertokens_received_daily_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='player',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='friend',
            new_name='player2',
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('player1', 'player2')},
        ),
        migrations.AddField(
            model_name='friendship',
            name='step_multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
