# Generated by Django 4.0.5 on 2022-07-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0007_remove_weathertokens_received_daily_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathertokens',
            name='id',
        ),
        migrations.AlterField(
            model_name='weathertokens',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='social_app.player'),
        ),
    ]
