# Generated by Django 4.0.5 on 2022-07-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0008_remove_weathertokens_id_alter_weathertokens_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathertokens',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='social_app.player'),
        ),
    ]
