# Generated by Django 4.0.5 on 2022-07-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0009_match_current_scene_player_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sceneChanges',
            field=models.BooleanField(default=False),
        ),
    ]
