# Generated by Django 4.0.5 on 2022-07-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0011_rename_player_friendship_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathertokens',
            name='used_shared',
            field=models.BooleanField(default=False),
        ),
    ]
