# Generated by Django 4.0.5 on 2022-07-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0010_match_scenechanges'),
        ('social_app', '0012_weathertokens_used_shared'),
    ]

    operations = [
    ]
